### ISSUE TITLE
rev_D :: Suggestions

### ISSUE THREAD

**Issue by mojamil** [TimMarder/determinants--marderT_canaleB_liuA_hasanA#7]
I suggest including some summary statistics with your numerical fields with the charts (for example the average number of occupants involved in a car crash)
I can't tell how you intended to use the population pyramid, but I suggest using it to compare to values of the same category, for example, you can compare the number of accidents of Honda cars vs the number of accidents of BMW cars per model year(like how the example compares population by gender per year).

**Comment by PGreatness** [comment]
Noted. We had talked about including summary statistics and was going to, but unfortunately the deadline came in too quickly for us. Thank you.
